name: umiuni2d_sprite_flutter
description: A new Flutter project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  umiuni2d_sprite:
    path: ../umiuni2d_sprite

dev_dependencies:
  test: ^0.12.0

