name: umiuni2d_sprite_flutter
description: A new Flutter project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  umiuni2d_sprite:
    git:
      url: https://github.com/kyorohiro/umiuni2d_sprite.git
      ref: v0.0.3

dev_dependencies:
  test: ^0.12.0

